# Raise built-in exception 'NameError'
raise NameError('An exception occured!')

# Output:
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# NameError: An exception occured!